# 服务配置
server:
  # 端口
  port: 8080
  servlet:
    # 访问上下文前缀
    context-path: /api
# 全局配置
spring:
  application:
    name: xiaomayi-monitor
  #  main:
  #    allow-bean-definition-overriding: true
  # 全局配置文件
  config:
    # 导入配置文件
    import:
      # actuator监控文件
      - configs/application-actuator.yml
  # 运行环境 local|dev|test|uat|prod,根据active动态加载YML配置文件
  profiles:
    active: @package.environment@
  # 国际化资源
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
  # 文件上传配置
  servlet:
    # 设置最大文件上传大小为10MB
    multipart:
      # 开启上传文件配置
      enabled: true
      # 文件上传临时保存位置，没有写入最终保存位置时存放的位置;
      location: /data/
      # 上传单个文件最大大小，设置-1表示不限制
      max-file-size: 10MB
      # 上传一组文件最大大小，设置-1表示不限制
      max-request-size: 10MB
      # 是否延迟解析，相当于懒加载
      resolve-lazily: false
      # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，默认为0
      file-size-threshold: 0
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 开发工具
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true
      # 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
      #exclude: WEB-INF/**,static/**
      # 监控额外的路径（优先于exclude）
      #additional-paths: src/main/java