# 全局配置
spring:
  application:
    name: xiaomayi-admin
  #  main:
  #    allow-bean-definition-overriding: true
  # 全局配置文件
  config:
    # 导入配置文件
    import:
      # Mybatis配置文件
      - configs/application-mybatis.yml
      # 日志配置文件
      - configs/application-logger.yml
      # 安全认证配置文件
      - configs/application-security.yml
      # 在线文档配置文件
      - configs/application-springdoc.yml
      # knife4j配置文件
      - configs/application-knife4j.yml
      # freemarker模板引擎配置文件
      - configs/application-freemarker.yml
      # thymeleaf模板引擎配置文件
      - configs/application-thymeleaf.yml
      # 多租户配置文件
      - configs/application-tenant.yml
      # actuator监控文件
      - configs/application-actuator.yml
      # 微信支付、支付宝支付配置文件
      - configs/application-pay.yml
  # 运行环境 local|dev|test|uat|prod,根据active动态加载YML配置文件
  profiles:
    active: @package.environment@
  # 国际化资源
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
  # 文件上传配置
  servlet:
    # 设置最大文件上传大小为10MB
    multipart:
      # 开启上传文件配置
      enabled: true
      # 文件上传临时保存位置，没有写入最终保存位置时存放的位置;
      location: /data/
      # 上传单个文件最大大小，设置-1表示不限制
      max-file-size: 10MB
      # 上传一组文件最大大小，设置-1表示不限制
      max-request-size: 10MB
      # 是否延迟解析，相当于懒加载
      resolve-lazily: false
      # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，默认为0
      file-size-threshold: 0
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 开发工具
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true
      # 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
      #exclude: WEB-INF/**,static/**
      # 监控额外的路径（优先于exclude）
      #additional-paths: src/main/java

##Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
#management:
#  endpoints:
#    web:
#      exposure:
#        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
#        include: "*"
#  endpoint:
#    health:
#      # 是否展示健康检查详情
#      show-details: ALWAYS
#
## info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
#info:
#  version: @project.version@
#  groupId: @project.groupId@
#  artifactId: @project.artifactId@