# Gitee授权
gitee:
  # 客户端ID
  clientId:
  # 客户端秘钥
  clientSecret:
  # 重定向地址
  redirectUri: https://www.xiaomayicloud.com
  # 认证授权URL
  accessTokenUrl: https://gitee.com/oauth/token
  # API地址
  apiURL: https://gitee.com/api/v5