# 令牌配置
token:
  # 自定义令牌标识
  header: Authorization
  # 签发者
  issuer: 小蚂蚁云
  # 令牌密钥
  secret: 9AE3C871045CD45582D8732DCA6E4981
  # 令牌有效期，默认60分钟
  expireTime: 1440
  # 令牌续签刷新时间，默认10分钟
  refreshTime: 30
  # 密码设置
  password:
    # 密码错误重试最大次数
    maxRetryCount: 5
    # 密码锁定时间，默认10分钟
    lockTime: 10