spring:
  #邮件配置
  mail:
    # 邮箱服务器地址
    host: smtp.163.com
    # 邮箱授权码，开启邮箱POP3/SMTP服务，获取客户端授权码(注意并不是邮箱密码，而是授权码)
    password: LRDVCLVARJNXGPVE
    # 邮箱的用户名
    username: xiaomayicloud@163.com
    # 使用SMTPS协议465端口,本地可以使用25
    port: 25
    # ssl 配置
    properties:
      # 开启邮件debug
      mail.debug: true
      # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      encoding: UTF-8
      # 开启SSL
      mail.smtp.ssl.enable: true
      # 设置是否需要认证，如果为true,那么用户名和密码就必须的。如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
      mail.smtp.auth: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false