spring:
  # Spring Boot Admin 配置项
  boot:
    admin:
      # 客户端开关
      enabled: true
      ui:
        title: 小蚂蚁云服务监控中心
      notify:
        mail:
          enabled: false
          from: xiaomayicloud@163.com
          to: 12345678@qq.com
      # Spring Boot Admin Server 服务端的相关配置
      context-path: admin # 配置 Spring
      monitor:
        # 监控发送请求的超时时间
        default-timeout: 20000
      # 配置一个账号和密码
      security:
        user:
          name: admin
          password: 123456