spring:
  application:
    name: xiaomayi-admin
  # Spring Boot Admin 配置项
  boot:
    admin:
      # 客户端开关
      enabled: true
      # Spring Boot Admin Server 服务端的相关配置
      context-path: admin # 配置 Spring
      # Spring Boot Admin Client 客户端的相关配置
      client:
        # 监控服务端口号
        port: 8080
        # 设置 Spring Boot Admin Server 地址
        url: http://127.0.0.1:${spring.boot.admin.client.port}/api/${spring.boot.admin.context-path}
        # 配置 admin-server的账号和密码
        username: admin
        password: 123456
        instance:
          service-host-type: IP # 注册实例时，优先使用 IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
          # 注册到admin server的微服务名称
          name: 小蚂蚁云后端管理系统
          metadata:
            # 这里配置admin-client的账号和密码
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}

  # 配置一个账号和密码
  security:
    user:
      name: admin
      password: 123456

# Actuator 监控端点的配置项
management:
  health:
    redis:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。、
    # 是否开启默认端点，默认值true
    enabled-by-default: true
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
    info: # 端点名称
      # 是否开放,对单一端点的开启与关闭
      enabled: true
    logfile:
      external-file: ${user.dir}/logs/${spring.profiles.active}/xs-monitor/xs-monitor-server/sys-console.log
  security:
    enabled: false

# 与监控相关的配置key都是以management开头
# 每一个端点就表示一个单独模块的功能,这些监控端点官网都有
# https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/actuator.html#actuator.endpoints
# 端点的访问格式: http://localhost:8080/actuator/端点名称/端点子属性
# 显示所有暴露的端点: http://localhost:8080/actuator/
# 常用的端点
# 1. beans: spring中完整的bean列表
# 2. conditions: 自动装配的条件信息,匹配成功和不匹配的原因
# 3. configprops: 显示所有的@ConfigProperties
# 4. env: 暴露spring的环境对象
# 5. health: 显示应用程序运行状态(重要)
# 6. info: 应用程序信息
# 7. loggers: 显示和修改应用程序中的日志配置
# 8. metrics: 应用程序的指标信息(重要)
# 9. mappings: 显示所有RequestMapping列表
# 10. scheduledtasks: 显示应用程序中的定时任务
# 11. sessions: 允许从Spring Session支持的会话存储中检索和删除会话
# 12. shutdown: 使应用程序正常关闭,默认禁用