# Mybatis配置文件
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaomayi.**.entity
  # XML扫描，找到所有的mapper.xml映射文件,多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  #configLocation: classpath:mybatis/mybatis-config.xml
  # MyBatis 原生支持的配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    cache-enabled: false
    use-generated-keys: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: false
    # 日志打印， 这个配置会将执行的sql打印出来，在开发或测试的时候可以用,
    # 生成环境建议关闭，设置：org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置JdbcTypeForNull, oracle数据库必须配置,解决oracle更新数据为null时无法转换报错,mysql不会出现此情况
    jdbc-type-for-null: null
  # 以下配置均有默认值,可以不设置
  global-config: # 全局策略配置
    # 关闭MP3.0+自带的banner
    banner: false
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: auto
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      # 驼峰下划线转换,表名是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      #是否开启大写命名，默认不开启
      capital-mode: false
      # 逻辑删除配置
      logic-delete-field: del_flag    # 全局逻辑删除的实体字段名
      logic-delete-value: 1          # 逻辑删除全局值（1表示已删除，默认为 1）
      logic-not-delete-value: 0      # 逻辑未删除全局值（0表示未删除，默认为 0）