# 支付宝支付
alipay:
  # 网关地址
  gatewayUrl: https://openapi.alipay.com/gateway.do
  # APP支付宝支付业务：app_id
  alipayAppId:
  # 商户的私钥,使用支付宝自带的openssl工具生成
  privateKey:
  # 应用的公钥，无需修改该值
  publicKey:
  # 支付宝的公钥，去open.alipay.com对应应用下查看
  alipayPublicKey:
  # 支付回调地址
  notifyUrl:
  # 付款成功后,页面重定向通知
  returnUrl:
  # 签名算法类型(根据生成私钥的算法,RSA2或RSA)
  signType: RSA2
  # 返回格式(JSON或XML)
  format: json
  # 字符编码格式
  charset: UTF-8

# 微信支付
wxpay:
  # 应用ID
  appId:
  # 应用秘钥
  appKey:
  # 商户ID
  mchId:
  # 支付证书路径
  certPath:
  # 通知回调地址
  notifyUrl:
  # 交易类型
  tradeType: NATIVE