spring:
  # 模板配置
  freemarker:
    # 是否允许mvc使用freemarker
    enabled: false
    # 指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: false
    # 是否开启template caching
    cache: false
    check-template-location: true
    # 设定Template的编码
    charset: UTF-8
    # 设置响应的内容类型
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    # 后缀名freemarker默认后缀为.ftl，当然你也可以改成自己习惯的.html
    suffix: .ftl
    # 设定模板的加载路径，多个以逗号分隔，默认: [“classpath:/templates/”]
    template-loader-path: classpath:/templates
    # 设置静态文件路径，js,css等
    mvc:
      static-path-pattern: /static/**