# 安全配置
security:
  # 放行URL配置
  ignored-urls:
    - /demo/**
    - /websocket/**
    - /gitee/**
    - /error
    - /login
    - /register
    - /captcha
    - /actuator
    - /actuator/**
    - /admin
    - /admin/**
    - /instances
    - /instances/**
    - /druid/**
    - /doc.html
    - /v3/api-docs/**
    - /webjars/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /file/**
    - /favicon.ico
    - /*.html
    - /*.css
    - /*.js