# 服务配置
server:
  # 端口
  port: 8083
  servlet:
    # 访问上下文前缀
    context-path: 

spring:
  # 全局配置
  config:
    # 导入配置
    import:
      # redis缓存配置，按需引入
      - configs/test/application-redis.yml
      # 邮件配置，按需引入
      - configs/test/application-email.yml
      # 阿里云OSS、SMS配置，按需引入
      - configs/test/application-aliyun.yml
      # Minio文件存储配置，按需引入
      - configs/test/application-minio.yml
      # Elastic搜索引擎配置，按需引入
      - configs/test/application-elastic.yml
      # 钉钉消息配置，按需引入
      - configs/test/application-dingtalk.yml
      # 令牌配置，按需引入
      - configs/test/application-token.yml
  # 数据源配置
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 设置默认的数据源或者数据源组,默认值为master
      primary: master
      # 严格匹配数据源,默认false,true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      # 多数据源支持，切记实际使用时按需使用，不需要的数据源注释掉
      datasource:
        # 主数据库MySQL
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/xiaomayi.elevue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root
#        # 从数据库MySQL,切记主从库时从库与主库表结构一致
#        slave:
#          enabled: false
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/xiaomayi.elevue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: root
#          password: root
#        # 数据库PG
#        postgres:
#          enabled: false
#          driverClassName: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/xiaomayi.elevue?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
#          username: postgres
#          password: 123456
#        # 数据库MSSQL
#        sqlserver:
#          enabled: false
#          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://localhost:1433;DatabaseName=xiaomayi.elevue;SelectMethod=cursor;encrypt=false;rewriteBatchedStatements=true
#          username: sa
#          password: 123456
#        # 数据库Sqlite
#        sqlite:
#          enabled: false
#          driverClassName: org.sqlite.JDBC
#          #          url: jdbc:sqlite::resource:db/xiaomayi.elevue.db;
#          url: jdbc:sqlite:D:/xiaomayi.elevue.db?date_string_format=yyyy-MM-dd HH:mm:ss
#          username: root
#          password: 123456
    # Druid的其他属性配置 springboot3整合情况下,数据库连接信息必须在Druid属性下
    druid:
      # 初始连接物理个数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间，单位毫秒
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 SELECT 1 FROM DUAL)
      validationQuery: SELECT 1 FROM DUAL
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnBorrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      poolPreparedStatements: true
      # 配置监控统计拦截的filters：去掉后监控界面sql无法统计，'wall'用于防火墙，stat:监控统计、self4j(使用log4j的记得导入log4j的依赖）：日志记录、wall：防御sql注入 此处配置不能遗漏服务sql监控台不能监控sql
      filters: stat,wall,log4j
      # 保持长连接
      keepAlive: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      webStatFilter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
      # 配置DruidStatViewServlet
      statViewServlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 
        # IP黑名单 (共同存在时，deny优先于allow)
        deny:
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 控制台登录名，默认为root
        login-username: admin
        # 控制台登录密码
        login-password: 123456
      # 配置过滤
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          enabled: true
          config:
            multi-statement-allow: true

# 系统配置
system:
  # 软件名称
  name: 小蚂蚁云
  # 软件版本
  version: 2.0.0
  # 本地存储路径
  profile: /opt/apps/upload/
  # 本地资源访问域名
  domain: http://127.0.0.1:8083/api/file
  # 演示环境
  demo: false

# 代码工具
generator:
  # 软件作者
  author: 小蚂蚁云团队
  # 生成代码存储模块，实际使用时根据需要自行修改
  serviceModelName: xiaomayi-services/xiaomayi-system
  # 生成文件包路径，实际使用时根据需要自行修改
  servicePackageName: com.xiaomayi.system
  # 生成代码存储模块，实际使用时根据需要自行修改
  moduleModelName: xiaomayi-modules/xiaomayi-admin
  # 生成文件包路径，实际使用时根据需要自行修改
  modulePackageName: com.xiaomayi.admin
  # 生成文件是否去除前缀，默认是false
  removePrefix: true
  # 数据表前缀，多个逗号“,”分割
  tablePrefix: sys_,gen_,qrtz_,cms_